// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type {
  Bit,
  Char,
  CodecTypes as PgTypes,
  Interval,
  JsonValue,
  Numeric,
  Time,
  TimeString,
  Timestamp,
  TimestampString,
  Timestamptz,
  TimestamptzString,
  Timetz,
  VarBit,
  Varchar,
} from '@prisma/orm-postgres/target/codec-types';
import type { QueryOperationTypes as PgTargetQueryOps } from '@prisma/orm-postgres/target/operation-types';

import type {
  ContractWithTypeMaps,
  RelationKeys,
  TypeMaps as TypeMapsType,
} from '@prisma/orm-postgres/family-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma/orm-postgres/contract/types';

export type StorageHash =
  StorageHashBase<'8c649b006e9462a1791ad51902243b91199196e61f1fb970ba075aad7a07bf71'>;
export type ExecutionHash =
  ExecutionHashBase<'ea6bc23da1a68707b855fb32d87ec1d871779f076bfd5e63a97ffc31d2290037'>;
export type ProfileHash =
  ProfileHashBase<'3916f444a8a17ad749191acf9e08dad97d1a327b88c2f1d45d12f240296aa8b2'>;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgTargetQueryOps<CodecTypes>;
export type AggregateTypes = {
  readonly avg: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
    };
  };
  readonly avgDecimal: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
    };
  };
  readonly count: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
  };
  readonly countBigInt: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
  };
  readonly max: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-date@1': {
        readonly output: 'pg/timestamptz-date@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly min: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-date@1': {
        readonly output: 'pg/timestamptz-date@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly sum: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
    };
  };
  readonly sumBigInt: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
    };
  };
};
type DefaultLiteralValue<CodecId extends string, Encoded> = CodecId extends keyof CodecTypes
  ? Encoded extends CodecTypes[CodecId]['json']
    ? Encoded
    : CodecTypes[CodecId]['json']
  : Encoded;

export type FieldOutputTypes = {
  readonly public: {
    readonly cola: {
      readonly compradorId: CodecTypes['pg/text@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly estado: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly pagoExpiraEn: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
      readonly posicion: CodecTypes['pg/int4@1']['output'];
      readonly productoId: CodecTypes['pg/text@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['output'];
    };
    readonly reporte: {
      readonly categoria: CodecTypes['pg/text@1']['output'];
      readonly categoriaNombre: CodecTypes['pg/text@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly detalle: CodecTypes['pg/text@1']['output'] | null;
      readonly elemento: CodecTypes['pg/text@1']['output'];
      readonly estado: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly mensajeId: CodecTypes['pg/text@1']['output'] | null;
      readonly productoId: CodecTypes['pg/text@1']['output'] | null;
      readonly reportadoPorId: CodecTypes['pg/text@1']['output'];
      readonly reportadoPorTipo: CodecTypes['pg/text@1']['output'];
      readonly sujetoId: CodecTypes['pg/text@1']['output'];
      readonly sujetoTipo: CodecTypes['pg/text@1']['output'];
      readonly tipoFalta: CodecTypes['pg/text@1']['output'];
      readonly tipoReportado: CodecTypes['pg/text@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly vendedorId: CodecTypes['pg/int4@1']['output'];
      readonly ventaId: CodecTypes['pg/text@1']['output'] | null;
    };
    readonly usuario: {
      readonly aceptaTerminos: CodecTypes['pg/bool@1']['output'];
      readonly codigoCorreo: CodecTypes['pg/text@1']['output'] | null;
      readonly codigoCorreoExpira: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
      readonly codigoRecuperacion: CodecTypes['pg/text@1']['output'] | null;
      readonly codigoRecuperacionExpira: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
      readonly correo: CodecTypes['pg/text@1']['output'];
      readonly correoVerificado: CodecTypes['pg/bool@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly curp: CodecTypes['pg/text@1']['output'] | null;
      readonly diasSinConfirmarHorario: CodecTypes['pg/int4@1']['output'];
      readonly direccion: CodecTypes['pg/text@1']['output'];
      readonly faltasLeves: CodecTypes['pg/int4@1']['output'];
      readonly horarioConfirmadoEn: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
      readonly horarios: CodecTypes['pg/json@1']['output'];
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly ineCodigoReverso: CodecTypes['pg/text@1']['output'] | null;
      readonly ineFrente: CodecTypes['pg/text@1']['output'];
      readonly ineReverso: CodecTypes['pg/text@1']['output'];
      readonly nombreCompleto: CodecTypes['pg/text@1']['output'];
      readonly password: CodecTypes['pg/text@1']['output'];
      readonly paypalEmail: CodecTypes['pg/text@1']['output'];
      readonly recibirNotificacionesCriticas: CodecTypes['pg/bool@1']['output'];
      readonly recibirNotificacionesPublicitarias: CodecTypes['pg/bool@1']['output'];
      readonly rfc: CodecTypes['pg/text@1']['output'];
      readonly telefono: CodecTypes['pg/text@1']['output'];
      readonly tipo: CodecTypes['pg/text@1']['output'];
      readonly totalReportes: CodecTypes['pg/int4@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly ventasExitosas: CodecTypes['pg/int4@1']['output'];
    };
    readonly venta: {
      readonly compradorId: CodecTypes['pg/text@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly estado: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly monto: CodecTypes['pg/float8@1']['output'];
      readonly paypalOrderId: CodecTypes['pg/text@1']['output'];
      readonly productoId: CodecTypes['pg/text@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly vendedorId: CodecTypes['pg/int4@1']['output'];
    };
  };
};
export type FieldInputTypes = {
  readonly public: {
    readonly cola: {
      readonly compradorId: CodecTypes['pg/text@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly estado: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly pagoExpiraEn: CodecTypes['pg/timestamptz-temporal@1']['input'] | null;
      readonly posicion: CodecTypes['pg/int4@1']['input'];
      readonly productoId: CodecTypes['pg/text@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['input'];
    };
    readonly reporte: {
      readonly categoria: CodecTypes['pg/text@1']['input'];
      readonly categoriaNombre: CodecTypes['pg/text@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly detalle: CodecTypes['pg/text@1']['input'] | null;
      readonly elemento: CodecTypes['pg/text@1']['input'];
      readonly estado: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly mensajeId: CodecTypes['pg/text@1']['input'] | null;
      readonly productoId: CodecTypes['pg/text@1']['input'] | null;
      readonly reportadoPorId: CodecTypes['pg/text@1']['input'];
      readonly reportadoPorTipo: CodecTypes['pg/text@1']['input'];
      readonly sujetoId: CodecTypes['pg/text@1']['input'];
      readonly sujetoTipo: CodecTypes['pg/text@1']['input'];
      readonly tipoFalta: CodecTypes['pg/text@1']['input'];
      readonly tipoReportado: CodecTypes['pg/text@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly vendedorId: CodecTypes['pg/int4@1']['input'];
      readonly ventaId: CodecTypes['pg/text@1']['input'] | null;
    };
    readonly usuario: {
      readonly aceptaTerminos: CodecTypes['pg/bool@1']['input'];
      readonly codigoCorreo: CodecTypes['pg/text@1']['input'] | null;
      readonly codigoCorreoExpira: CodecTypes['pg/timestamptz-temporal@1']['input'] | null;
      readonly codigoRecuperacion: CodecTypes['pg/text@1']['input'] | null;
      readonly codigoRecuperacionExpira: CodecTypes['pg/timestamptz-temporal@1']['input'] | null;
      readonly correo: CodecTypes['pg/text@1']['input'];
      readonly correoVerificado: CodecTypes['pg/bool@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly curp: CodecTypes['pg/text@1']['input'] | null;
      readonly diasSinConfirmarHorario: CodecTypes['pg/int4@1']['input'];
      readonly direccion: CodecTypes['pg/text@1']['input'];
      readonly faltasLeves: CodecTypes['pg/int4@1']['input'];
      readonly horarioConfirmadoEn: CodecTypes['pg/timestamptz-temporal@1']['input'] | null;
      readonly horarios: CodecTypes['pg/json@1']['input'];
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly ineCodigoReverso: CodecTypes['pg/text@1']['input'] | null;
      readonly ineFrente: CodecTypes['pg/text@1']['input'];
      readonly ineReverso: CodecTypes['pg/text@1']['input'];
      readonly nombreCompleto: CodecTypes['pg/text@1']['input'];
      readonly password: CodecTypes['pg/text@1']['input'];
      readonly paypalEmail: CodecTypes['pg/text@1']['input'];
      readonly recibirNotificacionesCriticas: CodecTypes['pg/bool@1']['input'];
      readonly recibirNotificacionesPublicitarias: CodecTypes['pg/bool@1']['input'];
      readonly rfc: CodecTypes['pg/text@1']['input'];
      readonly telefono: CodecTypes['pg/text@1']['input'];
      readonly tipo: CodecTypes['pg/text@1']['input'];
      readonly totalReportes: CodecTypes['pg/int4@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly ventasExitosas: CodecTypes['pg/int4@1']['input'];
    };
    readonly venta: {
      readonly compradorId: CodecTypes['pg/text@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly estado: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly monto: CodecTypes['pg/float8@1']['input'];
      readonly paypalOrderId: CodecTypes['pg/text@1']['input'];
      readonly productoId: CodecTypes['pg/text@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly vendedorId: CodecTypes['pg/int4@1']['input'];
    };
  };
};
export type StorageColumnTypes = {
  readonly public: {
    readonly cola: {
      readonly compradorId: CodecTypes['pg/text@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly estado: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly pagoExpiraEn: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
      readonly posicion: CodecTypes['pg/int4@1']['output'];
      readonly productoId: CodecTypes['pg/text@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['output'];
    };
    readonly reporte: {
      readonly categoria: CodecTypes['pg/text@1']['output'];
      readonly categoriaNombre: CodecTypes['pg/text@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly detalle: CodecTypes['pg/text@1']['output'] | null;
      readonly elemento: CodecTypes['pg/text@1']['output'];
      readonly estado: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly mensajeId: CodecTypes['pg/text@1']['output'] | null;
      readonly productoId: CodecTypes['pg/text@1']['output'] | null;
      readonly reportadoPorId: CodecTypes['pg/text@1']['output'];
      readonly reportadoPorTipo: CodecTypes['pg/text@1']['output'];
      readonly sujetoId: CodecTypes['pg/text@1']['output'];
      readonly sujetoTipo: CodecTypes['pg/text@1']['output'];
      readonly tipoFalta: CodecTypes['pg/text@1']['output'];
      readonly tipoReportado: CodecTypes['pg/text@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly vendedorId: CodecTypes['pg/int4@1']['output'];
      readonly ventaId: CodecTypes['pg/text@1']['output'] | null;
    };
    readonly usuario: {
      readonly aceptaTerminos: CodecTypes['pg/bool@1']['output'];
      readonly codigoCorreo: CodecTypes['pg/text@1']['output'] | null;
      readonly codigoCorreoExpira: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
      readonly codigoRecuperacion: CodecTypes['pg/text@1']['output'] | null;
      readonly codigoRecuperacionExpira: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
      readonly correo: CodecTypes['pg/text@1']['output'];
      readonly correoVerificado: CodecTypes['pg/bool@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly curp: CodecTypes['pg/text@1']['output'] | null;
      readonly diasSinConfirmarHorario: CodecTypes['pg/int4@1']['output'];
      readonly direccion: CodecTypes['pg/text@1']['output'];
      readonly faltasLeves: CodecTypes['pg/int4@1']['output'];
      readonly horarioConfirmadoEn: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
      readonly horarios: CodecTypes['pg/json@1']['output'];
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly ineCodigoReverso: CodecTypes['pg/text@1']['output'] | null;
      readonly ineFrente: CodecTypes['pg/text@1']['output'];
      readonly ineReverso: CodecTypes['pg/text@1']['output'];
      readonly nombreCompleto: CodecTypes['pg/text@1']['output'];
      readonly password: CodecTypes['pg/text@1']['output'];
      readonly paypalEmail: CodecTypes['pg/text@1']['output'];
      readonly recibirNotificacionesCriticas: CodecTypes['pg/bool@1']['output'];
      readonly recibirNotificacionesPublicitarias: CodecTypes['pg/bool@1']['output'];
      readonly rfc: CodecTypes['pg/text@1']['output'];
      readonly telefono: CodecTypes['pg/text@1']['output'];
      readonly tipo: CodecTypes['pg/text@1']['output'];
      readonly totalReportes: CodecTypes['pg/int4@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly ventasExitosas: CodecTypes['pg/int4@1']['output'];
    };
    readonly venta: {
      readonly compradorId: CodecTypes['pg/text@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly estado: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly monto: CodecTypes['pg/float8@1']['output'];
      readonly paypalOrderId: CodecTypes['pg/text@1']['output'];
      readonly productoId: CodecTypes['pg/text@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly vendedorId: CodecTypes['pg/int4@1']['output'];
    };
  };
};
export type StorageColumnInputTypes = {
  readonly public: {
    readonly cola: {
      readonly compradorId: CodecTypes['pg/text@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly estado: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly pagoExpiraEn: CodecTypes['pg/timestamptz-temporal@1']['input'] | null;
      readonly posicion: CodecTypes['pg/int4@1']['input'];
      readonly productoId: CodecTypes['pg/text@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['input'];
    };
    readonly reporte: {
      readonly categoria: CodecTypes['pg/text@1']['input'];
      readonly categoriaNombre: CodecTypes['pg/text@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly detalle: CodecTypes['pg/text@1']['input'] | null;
      readonly elemento: CodecTypes['pg/text@1']['input'];
      readonly estado: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly mensajeId: CodecTypes['pg/text@1']['input'] | null;
      readonly productoId: CodecTypes['pg/text@1']['input'] | null;
      readonly reportadoPorId: CodecTypes['pg/text@1']['input'];
      readonly reportadoPorTipo: CodecTypes['pg/text@1']['input'];
      readonly sujetoId: CodecTypes['pg/text@1']['input'];
      readonly sujetoTipo: CodecTypes['pg/text@1']['input'];
      readonly tipoFalta: CodecTypes['pg/text@1']['input'];
      readonly tipoReportado: CodecTypes['pg/text@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly vendedorId: CodecTypes['pg/int4@1']['input'];
      readonly ventaId: CodecTypes['pg/text@1']['input'] | null;
    };
    readonly usuario: {
      readonly aceptaTerminos: CodecTypes['pg/bool@1']['input'];
      readonly codigoCorreo: CodecTypes['pg/text@1']['input'] | null;
      readonly codigoCorreoExpira: CodecTypes['pg/timestamptz-temporal@1']['input'] | null;
      readonly codigoRecuperacion: CodecTypes['pg/text@1']['input'] | null;
      readonly codigoRecuperacionExpira: CodecTypes['pg/timestamptz-temporal@1']['input'] | null;
      readonly correo: CodecTypes['pg/text@1']['input'];
      readonly correoVerificado: CodecTypes['pg/bool@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly curp: CodecTypes['pg/text@1']['input'] | null;
      readonly diasSinConfirmarHorario: CodecTypes['pg/int4@1']['input'];
      readonly direccion: CodecTypes['pg/text@1']['input'];
      readonly faltasLeves: CodecTypes['pg/int4@1']['input'];
      readonly horarioConfirmadoEn: CodecTypes['pg/timestamptz-temporal@1']['input'] | null;
      readonly horarios: CodecTypes['pg/json@1']['input'];
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly ineCodigoReverso: CodecTypes['pg/text@1']['input'] | null;
      readonly ineFrente: CodecTypes['pg/text@1']['input'];
      readonly ineReverso: CodecTypes['pg/text@1']['input'];
      readonly nombreCompleto: CodecTypes['pg/text@1']['input'];
      readonly password: CodecTypes['pg/text@1']['input'];
      readonly paypalEmail: CodecTypes['pg/text@1']['input'];
      readonly recibirNotificacionesCriticas: CodecTypes['pg/bool@1']['input'];
      readonly recibirNotificacionesPublicitarias: CodecTypes['pg/bool@1']['input'];
      readonly rfc: CodecTypes['pg/text@1']['input'];
      readonly telefono: CodecTypes['pg/text@1']['input'];
      readonly tipo: CodecTypes['pg/text@1']['input'];
      readonly totalReportes: CodecTypes['pg/int4@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly ventasExitosas: CodecTypes['pg/int4@1']['input'];
    };
    readonly venta: {
      readonly compradorId: CodecTypes['pg/text@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly estado: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly monto: CodecTypes['pg/float8@1']['input'];
      readonly paypalOrderId: CodecTypes['pg/text@1']['input'];
      readonly productoId: CodecTypes['pg/text@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly vendedorId: CodecTypes['pg/int4@1']['input'];
    };
  };
};

export namespace Models {
  export type public_cola = {
    compradorId: CodecTypes['pg/text@1']['output'];
    createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    estado: CodecTypes['pg/text@1']['output'];
    id: CodecTypes['pg/int4@1']['output'];
    pagoExpiraEn: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
    posicion: CodecTypes['pg/int4@1']['output'];
    productoId: CodecTypes['pg/text@1']['output'];
    updatedAt: CodecTypes['pg/timestamptz-string@1']['output'];
    readonly [RelationKeys]?: never;
  };
  export type public_reporte = {
    categoria: CodecTypes['pg/text@1']['output'];
    categoriaNombre: CodecTypes['pg/text@1']['output'];
    createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    detalle: CodecTypes['pg/text@1']['output'] | null;
    elemento: CodecTypes['pg/text@1']['output'];
    estado: CodecTypes['pg/text@1']['output'];
    id: CodecTypes['pg/int4@1']['output'];
    mensajeId: CodecTypes['pg/text@1']['output'] | null;
    productoId: CodecTypes['pg/text@1']['output'] | null;
    reportadoPorId: CodecTypes['pg/text@1']['output'];
    reportadoPorTipo: CodecTypes['pg/text@1']['output'];
    sujetoId: CodecTypes['pg/text@1']['output'];
    sujetoTipo: CodecTypes['pg/text@1']['output'];
    tipoFalta: CodecTypes['pg/text@1']['output'];
    tipoReportado: CodecTypes['pg/text@1']['output'];
    updatedAt: CodecTypes['pg/timestamptz-string@1']['output'];
    vendedorId: CodecTypes['pg/int4@1']['output'];
    ventaId: CodecTypes['pg/text@1']['output'] | null;
    vendedor: public_usuario;
    readonly [RelationKeys]?: 'vendedor';
  };
  export type public_usuario = {
    aceptaTerminos: CodecTypes['pg/bool@1']['output'];
    codigoCorreo: CodecTypes['pg/text@1']['output'] | null;
    codigoCorreoExpira: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
    codigoRecuperacion: CodecTypes['pg/text@1']['output'] | null;
    codigoRecuperacionExpira: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
    correo: CodecTypes['pg/text@1']['output'];
    correoVerificado: CodecTypes['pg/bool@1']['output'];
    createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    curp: CodecTypes['pg/text@1']['output'] | null;
    diasSinConfirmarHorario: CodecTypes['pg/int4@1']['output'];
    direccion: CodecTypes['pg/text@1']['output'];
    faltasLeves: CodecTypes['pg/int4@1']['output'];
    horarioConfirmadoEn: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
    horarios: CodecTypes['pg/json@1']['output'];
    id: CodecTypes['pg/int4@1']['output'];
    ineCodigoReverso: CodecTypes['pg/text@1']['output'] | null;
    ineFrente: CodecTypes['pg/text@1']['output'];
    ineReverso: CodecTypes['pg/text@1']['output'];
    nombreCompleto: CodecTypes['pg/text@1']['output'];
    password: CodecTypes['pg/text@1']['output'];
    paypalEmail: CodecTypes['pg/text@1']['output'];
    recibirNotificacionesCriticas: CodecTypes['pg/bool@1']['output'];
    recibirNotificacionesPublicitarias: CodecTypes['pg/bool@1']['output'];
    rfc: CodecTypes['pg/text@1']['output'];
    telefono: CodecTypes['pg/text@1']['output'];
    tipo: CodecTypes['pg/text@1']['output'];
    totalReportes: CodecTypes['pg/int4@1']['output'];
    updatedAt: CodecTypes['pg/timestamptz-string@1']['output'];
    ventasExitosas: CodecTypes['pg/int4@1']['output'];
    reportes: public_reporte[];
    ventas: public_venta[];
    readonly [RelationKeys]?: 'reportes' | 'ventas';
  };
  export type public_venta = {
    compradorId: CodecTypes['pg/text@1']['output'];
    createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    estado: CodecTypes['pg/text@1']['output'];
    id: CodecTypes['pg/int4@1']['output'];
    monto: CodecTypes['pg/float8@1']['output'];
    paypalOrderId: CodecTypes['pg/text@1']['output'];
    productoId: CodecTypes['pg/text@1']['output'];
    updatedAt: CodecTypes['pg/timestamptz-string@1']['output'];
    vendedorId: CodecTypes['pg/int4@1']['output'];
    vendedor: public_usuario;
    readonly [RelationKeys]?: 'vendedor';
  };
}

export declare const models: {
  public: {
    cola: Models.public_cola;
    reporte: Models.public_reporte;
    usuario: Models.public_usuario;
    venta: Models.public_venta;
  };
};

export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes,
  AggregateTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly public: {
        readonly id: 'public';
        readonly kind: 'postgres-schema';
        readonly entries: {
          readonly table: {
            readonly cola: {
              columns: {
                readonly compradorId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly createdAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly estado: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', 'activa'>;
                  };
                };
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly pagoExpiraEn: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: true;
                };
                readonly posicion: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly productoId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly updatedAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly reporte: {
              columns: {
                readonly categoria: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly categoriaNombre: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly createdAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly detalle: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly elemento: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly estado: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', 'pendiente'>;
                  };
                };
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly mensajeId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly productoId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly reportadoPorId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly reportadoPorTipo: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly sujetoId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly sujetoTipo: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly tipoFalta: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly tipoReportado: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', 'vendedor'>;
                  };
                };
                readonly updatedAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                };
                readonly vendedorId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly ventaId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'reporte_vendedorId_idx_ee765345';
                  readonly prefix: 'reporte_vendedorId_idx';
                  readonly columns: readonly ['vendedorId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'reporte';
                    readonly columns: readonly ['vendedorId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'usuario';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly usuario: {
              columns: {
                readonly aceptaTerminos: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                };
                readonly codigoCorreo: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly codigoCorreoExpira: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: true;
                };
                readonly codigoRecuperacion: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly codigoRecuperacionExpira: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: true;
                };
                readonly correo: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly correoVerificado: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/bool@1', false>;
                  };
                };
                readonly createdAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly curp: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly diasSinConfirmarHorario: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/int4@1', 0>;
                  };
                };
                readonly direccion: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly faltasLeves: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/int4@1', 0>;
                  };
                };
                readonly horarioConfirmadoEn: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: true;
                };
                readonly horarios: {
                  readonly nativeType: 'json';
                  readonly codecId: 'pg/json@1';
                  readonly nullable: false;
                };
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly ineCodigoReverso: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly ineFrente: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly ineReverso: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly nombreCompleto: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly password: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly paypalEmail: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly recibirNotificacionesCriticas: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                };
                readonly recibirNotificacionesPublicitarias: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/bool@1', false>;
                  };
                };
                readonly rfc: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly telefono: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly tipo: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', 'vendedor'>;
                  };
                };
                readonly totalReportes: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/int4@1', 0>;
                  };
                };
                readonly updatedAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                };
                readonly ventasExitosas: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/int4@1', 0>;
                  };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['correo'] }];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly venta: {
              columns: {
                readonly compradorId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly createdAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly estado: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', 'completada'>;
                  };
                };
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly monto: {
                  readonly nativeType: 'float8';
                  readonly codecId: 'pg/float8@1';
                  readonly nullable: false;
                };
                readonly paypalOrderId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly productoId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly updatedAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                };
                readonly vendedorId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'venta_vendedorId_idx_ee765345';
                  readonly prefix: 'venta_vendedorId_idx';
                  readonly columns: readonly ['vendedorId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'venta';
                    readonly columns: readonly ['vendedorId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'usuario';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'postgres';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly cola: { readonly namespace: 'public' & NamespaceId; readonly model: 'cola' };
    readonly reporte: { readonly namespace: 'public' & NamespaceId; readonly model: 'reporte' };
    readonly usuario: { readonly namespace: 'public' & NamespaceId; readonly model: 'usuario' };
    readonly venta: { readonly namespace: 'public' & NamespaceId; readonly model: 'venta' };
  };
  readonly domain: {
    readonly namespaces: {
      readonly public: {
        readonly models: {
          readonly cola: {
            readonly fields: {
              readonly compradorId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly estado: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly pagoExpiraEn: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly posicion: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly productoId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'cola';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly compradorId: { readonly column: 'compradorId' };
                readonly createdAt: { readonly column: 'createdAt' };
                readonly estado: { readonly column: 'estado' };
                readonly id: { readonly column: 'id' };
                readonly pagoExpiraEn: { readonly column: 'pagoExpiraEn' };
                readonly posicion: { readonly column: 'posicion' };
                readonly productoId: { readonly column: 'productoId' };
                readonly updatedAt: { readonly column: 'updatedAt' };
              };
            };
          };
          readonly reporte: {
            readonly fields: {
              readonly categoria: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly categoriaNombre: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly detalle: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly elemento: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly estado: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly mensajeId: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly productoId: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly reportadoPorId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly reportadoPorTipo: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly sujetoId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly sujetoTipo: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly tipoFalta: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly tipoReportado: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly vendedorId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly ventaId: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly vendedor: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'usuario';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['vendedorId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'reporte';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly categoria: { readonly column: 'categoria' };
                readonly categoriaNombre: { readonly column: 'categoriaNombre' };
                readonly createdAt: { readonly column: 'createdAt' };
                readonly detalle: { readonly column: 'detalle' };
                readonly elemento: { readonly column: 'elemento' };
                readonly estado: { readonly column: 'estado' };
                readonly id: { readonly column: 'id' };
                readonly mensajeId: { readonly column: 'mensajeId' };
                readonly productoId: { readonly column: 'productoId' };
                readonly reportadoPorId: { readonly column: 'reportadoPorId' };
                readonly reportadoPorTipo: { readonly column: 'reportadoPorTipo' };
                readonly sujetoId: { readonly column: 'sujetoId' };
                readonly sujetoTipo: { readonly column: 'sujetoTipo' };
                readonly tipoFalta: { readonly column: 'tipoFalta' };
                readonly tipoReportado: { readonly column: 'tipoReportado' };
                readonly updatedAt: { readonly column: 'updatedAt' };
                readonly vendedorId: { readonly column: 'vendedorId' };
                readonly ventaId: { readonly column: 'ventaId' };
              };
            };
          };
          readonly usuario: {
            readonly fields: {
              readonly aceptaTerminos: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
              readonly codigoCorreo: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly codigoCorreoExpira: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly codigoRecuperacion: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly codigoRecuperacionExpira: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly correo: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly correoVerificado: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly curp: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly diasSinConfirmarHorario: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly direccion: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly faltasLeves: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly horarioConfirmadoEn: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly horarios: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/json@1' };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly ineCodigoReverso: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly ineFrente: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly ineReverso: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly nombreCompleto: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly password: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly paypalEmail: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly recibirNotificacionesCriticas: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
              readonly recibirNotificacionesPublicitarias: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
              readonly rfc: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly telefono: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly tipo: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly totalReportes: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly ventasExitosas: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
            };
            readonly relations: {
              readonly reportes: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'reporte';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['vendedorId'];
                };
              };
              readonly ventas: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'venta';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['vendedorId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'usuario';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly aceptaTerminos: { readonly column: 'aceptaTerminos' };
                readonly codigoCorreo: { readonly column: 'codigoCorreo' };
                readonly codigoCorreoExpira: { readonly column: 'codigoCorreoExpira' };
                readonly codigoRecuperacion: { readonly column: 'codigoRecuperacion' };
                readonly codigoRecuperacionExpira: { readonly column: 'codigoRecuperacionExpira' };
                readonly correo: { readonly column: 'correo' };
                readonly correoVerificado: { readonly column: 'correoVerificado' };
                readonly createdAt: { readonly column: 'createdAt' };
                readonly curp: { readonly column: 'curp' };
                readonly diasSinConfirmarHorario: { readonly column: 'diasSinConfirmarHorario' };
                readonly direccion: { readonly column: 'direccion' };
                readonly faltasLeves: { readonly column: 'faltasLeves' };
                readonly horarioConfirmadoEn: { readonly column: 'horarioConfirmadoEn' };
                readonly horarios: { readonly column: 'horarios' };
                readonly id: { readonly column: 'id' };
                readonly ineCodigoReverso: { readonly column: 'ineCodigoReverso' };
                readonly ineFrente: { readonly column: 'ineFrente' };
                readonly ineReverso: { readonly column: 'ineReverso' };
                readonly nombreCompleto: { readonly column: 'nombreCompleto' };
                readonly password: { readonly column: 'password' };
                readonly paypalEmail: { readonly column: 'paypalEmail' };
                readonly recibirNotificacionesCriticas: {
                  readonly column: 'recibirNotificacionesCriticas';
                };
                readonly recibirNotificacionesPublicitarias: {
                  readonly column: 'recibirNotificacionesPublicitarias';
                };
                readonly rfc: { readonly column: 'rfc' };
                readonly telefono: { readonly column: 'telefono' };
                readonly tipo: { readonly column: 'tipo' };
                readonly totalReportes: { readonly column: 'totalReportes' };
                readonly updatedAt: { readonly column: 'updatedAt' };
                readonly ventasExitosas: { readonly column: 'ventasExitosas' };
              };
            };
          };
          readonly venta: {
            readonly fields: {
              readonly compradorId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly estado: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly monto: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/float8@1' };
              };
              readonly paypalOrderId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly productoId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly vendedorId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
            };
            readonly relations: {
              readonly vendedor: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'usuario';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['vendedorId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'venta';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly compradorId: { readonly column: 'compradorId' };
                readonly createdAt: { readonly column: 'createdAt' };
                readonly estado: { readonly column: 'estado' };
                readonly id: { readonly column: 'id' };
                readonly monto: { readonly column: 'monto' };
                readonly paypalOrderId: { readonly column: 'paypalOrderId' };
                readonly productoId: { readonly column: 'productoId' };
                readonly updatedAt: { readonly column: 'updatedAt' };
                readonly vendedorId: { readonly column: 'vendedorId' };
              };
            };
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly checkConstraint: true;
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly insertOnConflictSkip: true;
      readonly insertOnConflictWithoutTarget: true;
      readonly lateral: true;
      readonly returning: true;
      readonly scalarList: true;
    };
  };
  readonly extensions: {};
  readonly execution: {
    readonly executionHash: ExecutionHash;
    readonly mutations: {
      readonly defaults: readonly [
        {
          readonly onCreate: { readonly id: 'timestampNow'; readonly kind: 'generator' };
          readonly onUpdate: { readonly id: 'timestampNow'; readonly kind: 'generator' };
          readonly ref: {
            readonly entry: 'cola';
            readonly field: 'updatedAt';
            readonly namespace: 'public';
          };
        },
        {
          readonly onCreate: { readonly id: 'timestampNow'; readonly kind: 'generator' };
          readonly onUpdate: { readonly id: 'timestampNow'; readonly kind: 'generator' };
          readonly ref: {
            readonly entry: 'reporte';
            readonly field: 'updatedAt';
            readonly namespace: 'public';
          };
        },
        {
          readonly onCreate: { readonly id: 'timestampNow'; readonly kind: 'generator' };
          readonly onUpdate: { readonly id: 'timestampNow'; readonly kind: 'generator' };
          readonly ref: {
            readonly entry: 'usuario';
            readonly field: 'updatedAt';
            readonly namespace: 'public';
          };
        },
        {
          readonly onCreate: { readonly id: 'timestampNow'; readonly kind: 'generator' };
          readonly onUpdate: { readonly id: 'timestampNow'; readonly kind: 'generator' };
          readonly ref: {
            readonly entry: 'venta';
            readonly field: 'updatedAt';
            readonly namespace: 'public';
          };
        },
      ];
    };
  };
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
